#!/usr/bin/perl

use strict;
use warnings;
no if $] >= 5.018, warnings => "experimental::smartmatch";
use IO::Zlib;

my @alllines;
my $dir = "/var/log/nginx";
opendir(DIR, $dir) or die "Couldn't open log directory ($dir): $! \n";
while (my $file = readdir(DIR)) {
	chomp($file);
	if ($file =~ /^access/) {
		if ($file =~ /\.gz$/) {
			my $fh = new IO::Zlib;
			if ($fh->open("$dir/$file", "rb")) {
				#print OUT <$fh>;
				while (my $line = <$fh>) {
					chomp($line);
					push @alllines, $line;
				}
				$fh->close;
			}
		} else {
			open FILE, "<$dir/$file" or die "Couldn't open log file: $! \n";
			#print OUT <FILE>;
			while (my $line = <FILE>) {
				chomp($line);
				push @alllines, <FILE>;
			}
			close FILE;
		}
	}
}
closedir(DIR);

my @outlines = &uniq(@alllines);
open OUT, ">/tmp/access_log" or die "Couldn't open output file for writing: $! \n";
print OUT join("\n",@outlines);
close OUT;

sub uniq(@) {
	my %seen;
	#grep !$seen{$_}++, @_;
	foreach my $l ( sort @_ ) {
		next if ($l =~ /^\s*$/);
		$seen{$l}++;
	}
	return keys %seen
}
